{{- range .Values.credentials }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: harmostes
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .store | default "bitwarden" }}
  target:
    name: {{ .name }}
    creationPolicy: {{ .creationPolicy | default "Owner" }}
    deletionPolicy: {{ .deletionPolicy | default "Retain" }}
    {{- with .template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        {{- toYaml .remoteRef | nindent 8 }}
    {{- end }}
{{- end }}
